### ISSUE TITLE
Integrate Slack and Github

### ISSUE THREAD

**Issue by LizNeeley** [LiminalCreations/ARIS-P3#2]
- [x] Should we create a separate channel for Github updates?

**Comment by guerrero-fj** [comment]
I wonder if we could use "Discussions" for our conversation trackers, and in lieu of slack for quick message exchange. We could have an open/ongoing discussion for Conversation Trackers and short discussions that can be closed at any moment once we agree that we have "discussed" the topic thoroughly or it has already derived into an issue with its corresponding action. I feel this way will be more organic and centralized. thoughts?

**Comment by LizNeeley** [comment]
Have integrated GitHub into Liminal Slack now
